### ISSUE TITLE
Map/15 Extension of the location overview

### ISSUE THREAD

**Issue by blackjack2693** [hpi-swt2/compass-portal-red#114]
(depends on location overview, issue #113 )

As a user I want to see more information about my destination and the way i take to it.

-   [x] distance to the destination I want to go to
-   [x]  displaying the distance in the mobile view
-   [ ]  info text to my location (if available)
-   [ ]  An icon of the type where I want to go

![pasted image 0](https://user-images.githubusercontent.com/35633229/148084354-63015781-5f05-4de7-bf8e-6c506b65e05a.png)

**Comment by ldreessen** [comment]
closed by PO
