### ISSUE TITLE
Sign in

### ISSUE THREAD

**Issue by valentindoering** [hpi-swt2/compass-portal-red#122]
As a user, when I open the application I want to sign in to my account via entering my email and password or via OpenID Connect

![Screenshot 2022-01-04 at 22 41 03](https://user-images.githubusercontent.com/54007786/148127508-b6b80e4c-ebf5-462d-83a9-547be7740c4c.png)

# Details
- Design Sign in page
- figure out how openID connect works - link to user account
- require this page, when opening the web app
- link to the search page after login
- display error message, if something went wrong

**Comment by lucasliebe** [comment]
Done are: 
- link to user account
- error message
- have this as root path

1. [ ] add rerouting to search page after login
2. [ ] add skip button and design layout
3. [ ] map user account to person with mail address
