### ISSUE TITLE
Options page

### ISSUE THREAD

**Issue by valentindoering** [hpi-swt2/compass-portal-red#123]
As an Admin, I want to see an options page as my starting point to manage the portal. As a signed in user I want to see an options page to edit personal information, contribute to the portal and so on. As a visitor, I want to get the option to sign in.

![Screenshot 2022-01-04 at 22 52 41](https://user-images.githubusercontent.com/54007786/148128708-46631764-2d16-472d-ab15-b895b200b7ac.png)
![Screenshot 2022-01-04 at 22 53 02](https://user-images.githubusercontent.com/54007786/148128752-6259ee7a-9db5-4a9b-802d-302984b2203b.png)
![Screenshot 2022-01-04 at 22 53 22](https://user-images.githubusercontent.com/54007786/148128784-b9037c1d-0b9b-4e0f-aa85-d7628cad67d6.png)

# Details
- #122 makes sure, that you know what people are logged in, create a table, that marks some users as admins
- design the page with the round image and the options, no button needs functionality yet
- "Sign in as Max Mustermann/ Peter Admin" should not be a button in the options page, as this is a prototype functionality

**Comment by tfiedlerdev** [comment]
# Still to be done
- [ ] Create different pages for users with admin role and normal users
- [ ] Display image of user
- [ ] write tests
