### ISSUE TITLE
Render search results on map

### ISSUE THREAD

**Issue by rsommerfeld** [hpi-swt2/compass-portal-red#165]
<img width="261" alt="Screenshot 2022-01-18 at 19 54 05" src="https://user-images.githubusercontent.com/55324905/150000758-310c4a1c-90d6-4264-8c4b-b5bdf1f6febf.png">

When trying to search on the map, I want to be able to actually see the search results.

**Pre-Context**:
- Search results are already available (a search query has been entered) in the code, in a similar format as to how they are available to the search result page
- There is already code for rendering points of interests as markers and for rendering a single room-result with the preview popup

**Post-Context**:
- Linking to Detailpages is already possible and the user will want to do it to make sense of search results.
- In the future there might be automatic focussing of the map or filtering of the visible pins for a better visual result.

**Acceptance Criteria**:
- [ ] For each search result a pin and the room name are rendered

**Comment by jannis-baum** [comment]
## adjusted acceptance

- [ ] pins / labels are rendered for all results that have location data and omitted for all others
