### ISSUE TITLE
No login? No sensible data!

### ISSUE THREAD

**Issue by valentindoering** [hpi-swt2/compass-portal-red#187]
We have 3 kinds of user in our system. 
Normalos (login, openid connect: students, profs, ...), Admins (extra admin features), Strangers (login skipped). 
We welcome unknowns, but we want them to be able to search only publicly available data. 
Normalos and Admins can see everything, but strangers should not be able to see students as search results!
Moreover, I will not only be able to exclude groups of people, but specific attributes on persons as well. Find a generic implementation for that, please. For this user story implement the example: Strangers should not be able to see students and  phone numbers attributes from persons in general. Excluded in search, map, detailpage, .....

**Comment by treyfel** [comment]
- [ ] Strangers can't find students as a query result
- [ ] Strangers can't see *attribute* of *group*
