### ISSUE TITLE
Initial search page to search in progress

### ISSUE THREAD

**Issue by valentindoering** [hpi-swt2/compass-portal-red#214]
#213 will give you a nice search page design, when there is no search query.
#search
When you click on the search bar (and start typing), however, the design should change, to effectively use the space to show you good results.
From to:
<img width="269" alt="Screenshot 2022-01-25 at 14 19 30" src="https://user-images.githubusercontent.com/54007786/150984254-0ab27b20-bd70-49b9-8589-833b5987b140.png">
<img width="307" alt="Screenshot 2022-01-25 at 14 19 54" src="https://user-images.githubusercontent.com/54007786/150984312-1286dcb7-1601-4749-8a9b-9190acc54e3c.png">

#213 and #163 will build for you the second search bar design.
Your task is to build a nice transition from the first to the second design and backwards. 
_"The search bar moves up and the platypus disappears"_
no complex animation, but a smooth minimalistic one

This is should be the last search design ticket, so please make the whole experience look smooth. If you have questions please ask.
- please add a "No results found" as search result, when the search query has no matches with entries from the database.
![Screenshot 2022-02-04 at 16 10 31](https://user-images.githubusercontent.com/54007786/152553962-a44dc383-ed59-4248-80d7-e1fbae1a547a.png)

Tasks
- [x] _"The search bar moves up and the platypus disappears"_
- [x] _"The search bar moves down and the platypus appears"_
- [x] No results found

**Comment by lucasliebe** [comment]
is done together with 213
