### ISSUE TITLE
Deplyoing on heroku fails because column "type" of relation "point_of_interests" does not exist

### ISSUE THREAD

**Issue by dieknolle3333** [hpi-swt2/compass-portal-red#225]
Moin, das Deployen auf Heroku schlägt aktuell fehl mit folgendem Fehler:
 remote: I, [2022-01-25T15:17:24.399367 #20]  INFO -- : Migrating to RemoveTypeFromPointOfInterests (20211211104503)        
remote: == 20211211104503 RemoveTypeFromPointOfInterests: migrating ===================        
remote: -- remove_column(:point_of_interests, :type, :string)        
remote: rails aborted!        
remote: StandardError: An error has occurred, this and all later migrations canceled:        
remote: 
remote: PG::UndefinedColumn: ERROR:  column "type" of relation "point_of_interests" does not exist  

Ich sehe in den Migrations zwei Migrations: Add Point Type to Point of Interest und Remove Point Type from Point of Interest 

In der ersten steht add_column :point_of_interests, :point_type, :string, null: false 

In der zweiten remove_column :point_of_interests, :type, :string 

(point_type != type)

Könnte das den Fehler verursachen? 😄

(Die Dateien wurden über diesen PR hinzugefügt, falls ihr danach sucht: https://github.com/hpi-swt2/compass-portal-red/pull/118)

**Comment by SebastianWagner2** [comment]
Das war's
