### ISSUE TITLE
Fix the navigation on the deployed version

### ISSUE THREAD

**Issue by blackjack2693** [hpi-swt2/compass-portal-red#248]
Currently the version deployed on the Heroku server does not work with the navigation. this needs to be addressed. This feature is implemented since a long time and should work flawlessly if deployed correctly. It is also an important keystone of the application. 
Nevertheless the autocorrection of the location input works and also the determination of the selected destination. 

- [x] The blue line does not appear on screen, it should
- [x] There are no directions, although there should be some

**Comment by NikkelM** [comment]
Works for me now, thanks @PaulVII
