### ISSUE TITLE
Map/1 Selecting a appropriate framework/lib

### ISSUE THREAD

**Issue by blackjack2693** [hpi-swt2/compass-portal-red#26]
As a user I want to be able to see a map of the HPI so that I have a chance to find a particular house. Without it I have not chance of knowing how to get anywhere.

**Comment by NikkelM** [comment]
@felix-20 @23mafi When are you planning to work on this? @PaulVII and I will start working on #28 on Friday afternoon, so it would be great to have some kind of working prototype to build upon :)

**Comment by felix-20** [comment]
We just published a first prototype, featuring a map on a page, you can find it on branch `map-1-first-hpi-map`, you probably need to execute `bundle install` to get the leaflet dependency

**Comment by blackjack2693** [comment]
This seems to be fairly complete and quite well understood.
