### ISSUE TITLE
Map/2 Names of buildings (and streets)

### ISSUE THREAD

**Issue by blackjack2693** [hpi-swt2/compass-portal-red#27]
As a user I want to be able to know which building is which to get to given place at HPI. Otherwise I have no idea where for example "Haus F" is.

**Comment by blackjack2693** [comment]
It would be nice if you do not see the names the whole time. For example, if you have a mask like the highlights the name should not be displayed. Otherwise the mask would cover the name completely or halfway.

**Comment by blackjack2693** [comment]
a nice reference might be the zoom level. The usefulness starts to dwindle at some scale. Also the indoor maps mostly need 
to be displayed if you are zoomed in.

**Comment by NikkelM** [comment]
Planning Poker (just edit this):
Nikkel: S
