### ISSUE TITLE
Map/3 Highlighting of buildings

### ISSUE THREAD

**Issue by blackjack2693** [hpi-swt2/compass-portal-red#28]
As a user I want to differentiate between buildings of the HPI, UP and other unrelated ones easily. They should be highlighted or otherwise marked brightly. (maybe kill in the analog plans all around campus.)

**Comment by blackjack2693** [comment]
The HPI buildings have to marked (preferably in orange, to avoid confusion)

**Comment by NikkelM** [comment]
Planning Poker (just edit this):
Nikkel: S

**Comment by NikkelM** [comment]
Closed with #84
