### ISSUE TITLE
Map/6 Navigation from the own location to a POI. 

### ISSUE THREAD

**Issue by blackjack2693** [hpi-swt2/compass-portal-red#37]
As a user unfamiliar with the HPI and the best ways to get around, I want to be able to navigate from one place on campus to another with a route, just like at google maps. I want to enter a POI (point of interest) or tap a buildings and hit navigate to get the shortest route there. it is enough if you only include routes outside of buildings (,<u>not</u> for example the route from campus 1 to 2 through the UP main building). it should display the route as a line in the map, preferrably in light blue to stay in line with other popular navigation services (not a must). entering a POI might seem difficult, but is a must. This should be possible by a search bar. (maybe a different team works on this i am not sure).
<img width="753" alt="image" src="https://user-images.githubusercontent.com/35633229/144295746-73862cb2-2452-423e-9f76-e92b404c30d1.png">

**Comment by blackjack2693** [comment]
to clarify, a line is preferred over the dotted line

**Comment by NikkelM** [comment]
Planning Poker (just edit this):
Nikkel: M

**Comment by NikkelM** [comment]
Also, I would suggest maybe splitting this story into two stories, where the base-story doesn't have the requirement of having a search-bar for entering POI's, as I think that that behaviour can be disconnected from the base functionality quite easily. (Base functionality would be clicking on a point on the map, I think @felix-20 already experimented with this) @hpi-swt2/fnhp21

**Comment by jannikgro** [comment]
Planning Poker: L
