### ISSUE TITLE
Map/7 Directions for navigation

### ISSUE THREAD

**Issue by blackjack2693** [hpi-swt2/compass-portal-red#38]
As a user who can not differentiate several different paths from each other on the navigation page, i want to get directions to my target. Otherwise i might take the wrong path. This should be a addition to the navigation by map and my own location.

A good description should include a text every time you have to change direction and include directions and distances to the next turn/action you have to take. this depends on issue #37

**Comment by NikkelM** [comment]
Planning Poker (just edit this):
Nikkel: L

**Comment by jannikgro** [comment]
Planning Poker: XL
