### ISSUE TITLE
Map/8 navigation from point to point

### ISSUE THREAD

**Issue by blackjack2693** [hpi-swt2/compass-portal-red#39]
I want to have the option to navigate in between POIs, for example to check a route I want to take later that day. it should display the route, preferrably in light blue to stay in line with other popular navigation services (not a must). to start this i also want to use the search bar to select the waypoints. after i added one i specify my second POI by an interface.

might depend on navigation #37 

<img width="391" alt="image" src="https://user-images.githubusercontent.com/35633229/144296590-628844db-a8e8-4b6c-b007-7407cad0cf69.png">

**Comment by NikkelM** [comment]
Planning Poker (just edit this):
Nikkel: M

**Comment by t-straeubig** [comment]
M

**Comment by PaulVII** [comment]
L
