### ISSUE TITLE
Map/9 HPI specific POIs 

### ISSUE THREAD

**Issue by blackjack2693** [hpi-swt2/compass-portal-red#40]
As a user looking for something, I want to see HPI specific POIs, like Mr Net. this should not block my view of the whole map, so it should be able to get toggled on and off by some events (like a particular zoom level) . They should be displayed as a dot on the map in a specified color of choice by the developer. this is similar to issue #17

To show it works a few important POIs should be cmapped, like Mr Net, the pavilion, etc.

**Comment by NikkelM** [comment]
@blackjack2693 I think the estimation of this story heavily depends on the extent/number of POI's needed to fulfil this story. I think we need to know what counts as a POI, and what doesn't. Also, what is meant by "colour of choice". I would interpret this as using one colour for all POI's, or should they be grouped by (to be defined) categories?

**Comment by jannikgro** [comment]
Planning Poker (assuming the list of POIs is given in the database and only the technical part is to do)
Jan: S
