### ISSUE TITLE
Map/10 Names for POIs 

### ISSUE THREAD

**Issue by blackjack2693** [hpi-swt2/compass-portal-red#41]
Display names for POIs and places of interest (like buildings), etc. This should look like a little text somewhere inside the borders for areas and next to POIs. this is similar to #13 and #27 

The labels need to be displayed next to the POI, big enough to read but not obstructing to much of the map. They should not show up all the time, only when deemed necessary by the program. As mentioned for areas of interest, the name should show up inside the borders, as long as this is still possible (i.e. if the building is not wide enough). If in doubt, think of the google maps text next to pins.

**Comment by felix-20** [comment]
Planning Poker:

Judith: XS (if we have #40 that is should be easy especially because we have done similar things in )
