### ISSUE TITLE
Make access rights to certain information possible

### ISSUE THREAD

**Issue by HerzogVonWiesel** [hpi-swt2/compass-portal-red#8]
8 PUNKTE

Gewisse Personen sollen nur auf gewisse Informationen Zugriff haben (ansehen bzw ändern)

(Bspw kann eine Person mit der Rolle "Professor" Informationen sehen, die ein Externer nicht sehen kann, während er zusätzlich mit der Rolle "HCI Leiter" alle Infos zum FG HCI ändern könnte)

**Comment by Zyranix** [comment]
I did some research how we could implement this; I found some gems that could do what we want:

1. [CanCanCan](https://github.com/CanCanCommunity/cancancan) can define permissions for user roles in a specific file and provides functionality to check whether the current user can do/view/anything/... something specific. I found [this blog article](https://blog.francium.tech/controlling-authorization-in-rails-with-cancancan-gem-1c2dfeecb26c) as an introductory tutorial helpful.
2. [Pundit](https://github.com/varvet/pundit) works similar, but every policy (~permission) is its own class (in contrast to CanCanCan, where everything is a single file). See also [this blog article](https://crypt.codemancers.com/posts/2018-07-29-leveraging-pundit/) for a tutorial.

See additionally [this article](https://blog.francium.tech/pundit-vs-cancancan-a-comparative-study-a8f7ab8f9ae8) for a comparison of CanCanCan and Pundit. Generally, Pundit makes it easier to write clean code and provide better structure, although CanCanCan seems to be easier to use. Functionality-wise there seems to be no meaningful difference.

**Comment by HerzogVonWiesel** [comment]
Close: Valentins Team will be working on this feature
