### ISSUE TITLE
Link detail page to navigation [3]

### ISSUE THREAD

**Issue by HerzogVonWiesel** [hpi-swt2/compass-portal-red#87]
As a user, I want to know how to get to the place (**room**) I have searched for. For this, it is necessary to have a  **button** on the detail page (similar to the following mockup, notice the blue arrow button), which on a tap/click, takes me to the navigation to said place [the navigation part itself is the work of **FNHP**, so it is needed to be in contact with them to have this link]

![image](https://user-images.githubusercontent.com/58423784/145563879-02a04468-5ad1-4590-b953-03bfd5555276.png)

**Comment by Zyranix** [comment]
Sorry, referenced wrong issue.
